version: "3.9"

services:
  apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    container_name: apache-web
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3
    container_name: mysql-laravel
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
